workspace = { members = [ "lib/firefly-ast","lib/firefly-parser", "lib/firefly-span", "lib/firefly-hir"] }
[package]
name = "inc"
version = "0.1.0"
edition = "2021"

[dependencies]
firefly-span = { path = "lib/firefly-span" }
firefly-parser = { path = "lib/firefly-parser" }
salsa = "0.16.1"
